<?php
/**
 * Pitchfork Glide - Carousel (Images)
 *
 * - Creates a carousel of images using glide.js
 *
 * @package pitchfork-glide
 */

/**
 * Set initial get_field declarations.
 */

/**
 * Set block classes
 * - Get additional classes from the 'advanced' field in the editor.
 * - Get alignment setting from toolbar if enabled in theme.json, or set default value
 * - Include any default classs for the block in the intial array.
 */

$block_attr = array( 'pf-carousel', 'pf-carousel-images', 'glide');
if ( ! empty( $block['className'] ) ) {
	$block_attr[] = $block['className'];
}

/**
 * Additional margin/padding settings
 * Returns a string for inclusion with style=""
 */
$spacing = pitchfork_blocks_acf_calculate_spacing( $block );

/**
 * Include block.json support for HTML anchor.
 */
$anchor = '';
if ( ! empty( $block['anchor'] ) ) {
	$anchor = 'id="' . $block['anchor'] . '"';
}

/**
 * Block logic here.
 */

/**
 * Create the outer wrapper for the block output.
 */
$attr  = implode( ' ', $block_attr );
$output = '<div ' . $anchor . ' class="' . $attr . '" style="' . $spacing . '">';

/**
 * Inner Block attributes, example templates and output string.
 */
$allowed_blocks = array( 'core/group', 'core/heading', 'core/paragraph', 'core/list' );
$template       = array(
	array(
		'core/heading',
		array(
			'level'   => 4,
			'content' => 'Template sample content',
		),
	),
);

$output .= '<InnerBlocks allowedBlocks="' . esc_attr( wp_json_encode( $allowed_blocks ) ) . '" template="' . esc_attr( wp_json_encode( $template ) ) . '" />';


/**
 * Close the block, echo the output.
 */
$output .= '</div>';

?>
	<div class="pf-carousel glide"
		data-glide-type="carousel"
		data-glide-per-view="3"
		data-glide-gap="16"
		data-glide-autoplay="4000"
		data-glide-hoverpause="true"
		data-glide-animation-duration="600"
		data-glide-breakpoints='{"1024":{"perView":2},"640":{"perView":1}}'>

		<div class="glide__track" data-glide-el="track">
			<ul class="glide__slides">
			<!-- Your InnerBlocks should render each slide as an <li class="glide__slide"> ... -->
				<li class="glide__slide"><img src="https://placehold.co/600x400/8c1d40/white?text=One" alt="placeholder 1"/></li>
				<li class="glide__slide"><img src="https://placehold.co/600x400/00a3e0/white?text=Two" alt="placeholder 2"/></li>
				<li class="glide__slide"><img src="https://placehold.co/600x400/e74973/white?text=Four" alt="placeholder 3... no 4"/></li>
			</ul>
		</div>

		<!-- Optional controls -->
		<div class="glide__arrows" data-glide-el="controls">
			<button class="glide__arrow glide__arrow--left" data-glide-dir="<">Prev</button>
			<button class="glide__arrow glide__arrow--right" data-glide-dir=">">Next</button>
		</div>

		<div class="glide__bullets" data-glide-el="controls[nav]">
			<!-- bullets auto-generated by you or the editor; can be empty -->
		</div>
	</div>

<?php

// echo $output;

